### PR TITLE
[release-4.11] OCPBUGS-21652: limit number of simultaneous client requests

### PR DESCRIPTION
**Pull request by simonpasquier**
Supersedes #86

### CODE REVIEW

**Review by raptorsun — APPROVED** [review]

**Comment by juzhao** [comment]
ci/prow/e2e-aws-ovn job [link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_k8s-prometheus-adapter/87/pull-ci-openshift-k8s-prometheus-adapter-master-e2e-aws-ovn/1715362637136531456)
```
Auto-merging pkg/client/api.go
Auto-merging pkg/client/limiter_test.go
CONFLICT (add/add): Merge conflict in pkg/client/limiter_test.go
Automatic merge failed; fix conflicts and then commit the result.
# Error: exit status 1
```

**Comment by jan--f** [comment]
@juzhao yeah I'd expect that to fail. Not sure why the test checks out the latest master commit of this repo (407cb1e10c7f37de218b13b2e34114cb3df79120) and then tries to merge the last commit in this PR (9c634bb04d7b54cf1af6c79dfd90f1f6f588de01) when the PR is against the `release-4.11` branch.

How about we ignore this failing test (its not required) and instead have a bug to fix the test?

**Comment by simonpasquier** [comment]
Hmm it's maybe some misconfiguration in openshift/release or bug in the CI operator?
From what I can tell, there's no `e2e-aws-ovn` job in the 4.11 release config (https://raw.githubusercontent.com/openshift/release/master/ci-operator/config/openshift/k8s-prometheus-adapter/openshift-k8s-prometheus-adapter-release-4.11.yaml).

**Comment by simonpasquier** [comment]
@juzhao check my last comment but I believe that the change is safe to go because `e2e-aws-ovn` shouldn't run here and there's already `e2e-aws` running the same test suite.

**Pull request merged**
