### PR TITLE
Populate both CPU and Memory resource container metrics if one is specified

### PR DESCRIPTION
**Pull request by joelsmith**
We're experiencing an issue where HPA won't work with pods that have init containers. The root cause seems to be that the init containers have memory metrics but no CPU metrics, and HPA refuses to take action if any containers in the pod have container metrics, but are missing either CPU or memory.

This patch makes the adapter metrics look like the metrics server endpoint.

Before:
```
items:
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: gerbil
    usage:
      cpu: "0"
      memory: 1568Ki
  - name: gerbil-init
    usage:
      memory: "0"
  kind: PodMetrics
```
After:
```
items:
- apiVersion: metrics.k8s.io/v1beta1
  containers:
  - name: gerbil
    usage:
      cpu: "0"
      memory: 1568Ki
  - name: gerbil-init
    usage:
      cpu: "0"
      memory: "0"
  kind: PodMetrics
```

### CODE REVIEW

**Comment by joelsmith** [comment]
@s-urbaniak PTAL. Am I supposed to make PRs against upstream https://github.com/DirectXMan12/k8s-prometheus-adapter first?

This is to fix https://bugzilla.redhat.com/show_bug.cgi?id=1867477

**Comment by s-urbaniak** [comment]
@joelsmith thank you a lot for the contribution! :tada: Yes, please a submit a PR against the upstream repository. Also please note that prometheus-adapter is going to be moved to the kubernetes-sigs organization soon. I see you are already in the Kubernetes org so I guess you have the CNCF CLA signed already.

**Comment by joelsmith** [comment]
@s-urbaniak  now that https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/330 has merged, what do I need to get this fixed in OCP? Do we start by merging this PR, or is there a different process for bringing code in from upstream?

**Comment by s-urbaniak** [comment]
@joelsmith a merge commit preserving the original commit hash is the way to go.

**Comment by s-urbaniak** [comment]
@joelsmith hmm, something is strange here as I see the same commits as in the already merged PR https://github.com/openshift/k8s-prometheus-adapter/pull/35 :thinking:

**Comment by joelsmith** [comment]
I had the merge backwards. I think I got it this time.

**Comment by s-urbaniak** [comment]
thank you! :tada:

**Pull request merged**
