### PR TITLE
Enable table display for pod and node metrics by bumping to latest sigs.k8s.io/metrics-server

### PR DESCRIPTION
**Pull request by smarterclayton**
Bump to the latest metrics-server to pick up changes to sort metrics output and display tabular results for `oc get nodemetrics`.

Bumped to 1.17 versions of custom-metrics-adapter and clients consistently and go 1.13.

TODO:
* [ ] There was one signature change to add label selector filtering on custom metrics that was not implemented yet

### CODE REVIEW

**Comment by smarterclayton** [comment]
```
$ oc get podmetrics -n openshift-monitoring
NAME                                           CPU   MEMORY     WINDOW
telemeter-client-d7457dd45-fgrqb               0     28872Ki    5m0s
alertmanager-main-1                            3m    50104Ki    5m0s
grafana-d559d94b6-p2q7f                        5m    48468Ki    5m0s
alertmanager-main-0                            3m    48776Ki    5m0s
openshift-state-metrics-77fc49d8dc-f56ng       0     29264Ki    5m0s
prometheus-operator-d4b779fb5-tjvhr            1m    23180Ki    5m0s
thanos-querier-68b49fcd75-8tblk                4m    50244Ki    5m0s
node-exporter-72s9l                            6m    19900Ki    5m0s
node-exporter-cfp5c                            7m    16628Ki    5m0s
prometheus-adapter-76d44687bd-x4jlm            0     19828Ki    5m0s
kube-state-metrics-b65d97cdf-bj9cr             0     39816Ki    5m0s
cluster-monitoring-operator-7589fb8d69-pl9lt   0     26052Ki    5m0s
node-exporter-pgrv4                            8m    19340Ki    5m0s
node-exporter-k4kqf                            11m   20656Ki    5m0s
prometheus-k8s-0                               71m   879420Ki   5m0s
node-exporter-h8ppf                            17m   19388Ki    5m0s
prometheus-adapter-76d44687bd-fs8ff            0     20784Ki    5m0s
prometheus-k8s-1                               64m   926864Ki   5m0s
alertmanager-main-2                            3m    51600Ki    5m0s
node-exporter-wqrms                            9m    19372Ki    5m0s
thanos-querier-68b49fcd75-v8nd4                2m    47288Ki    5m0s
```

**Comment by lilic** [comment]
I understand this is a do not merge thing, but doesn't say "don't comment" so commenting 😅 

This seems like a strange sorted output, considering you are sorting by names in the code 🤔? 
Alphabetical sort like when you do kubectl get pods/nodes is what I would expect here, or indeed the way it is when you do `kubectl get top pod` with no sort enabled.

**Comment by smarterclayton** [comment]
Agree.  Iin this case I think the bug is in pod metrics API Server itself - it's not sorting by namespace and then pod name like kube apis do.  Might be alongside the fix to upstream.

**Comment by smarterclayton** [comment]
```
oc get podmetrics -n openshift-monitoring
NAME                                           CPU   MEMORY     WINDOW
alertmanager-main-0                            0     21576Ki    5m0s
alertmanager-main-1                            9m    18012Ki    5m0s
alertmanager-main-2                            0     28000Ki    5m0s
cluster-monitoring-operator-7cd7c77658-5x8m9   11m   26032Ki    5m0s
grafana-585d499446-fs8p5                       4m    51952Ki    5m0s
kube-state-metrics-57995b7c87-lp6dt            3m    50864Ki    5m0s
node-exporter-492wr                            1m    40964Ki    5m0s
node-exporter-8x5kk                            53m   840544Ki   5m0s
node-exporter-dvgqt                            0     27304Ki    5m0s
node-exporter-gd7jj                            2m    50964Ki    5m0s
node-exporter-t4mj2                            5m    17444Ki    5m0s
node-exporter-zm9sk                            6m    19580Ki    5m0s
openshift-state-metrics-76869bfd9-jg8wl        0     20896Ki    5m0s
prometheus-adapter-7f6cd87fc8-52mbs            3m    55592Ki    5m0s
prometheus-adapter-7f6cd87fc8-smcp2            68m   824080Ki   5m0s
prometheus-k8s-0                               6m    19752Ki    5m0s
prometheus-k8s-1                               0     30700Ki    5m0s
prometheus-operator-8f8779c57-4tp9g            10m   19836Ki    5m0s
telemeter-client-7ff7f87f49-wks84              3m    50840Ki    5m0s
thanos-querier-556dc556b4-vplcs                3m    42476Ki    5m0s
thanos-querier-556dc556b4-vr2rj                11m   21012Ki    5m0s
```

going to open the upstream PRs

**Comment by smarterclayton** [comment]
Opened draft at https://github.com/kubernetes-sigs/metrics-server/pull/478

**Comment by smarterclayton** [comment]
Now that upstream is fixed I bumped and picked this up ready for 4.5.  Please review - I may need some guidance on expectation for the custom metrics interface change (to add labels) on how to fix that.

**Comment by lilic** [comment]
Nice!

> this up ready for 4.5. 

We should open this PR in https://github.com/DirectXMan12/k8s-prometheus-adapter Or do you want to address the TODO here before opening "upstream"?

**Comment by smarterclayton** [comment]
Upstream hasn't cut a tag for metrics-server yet, but there are no changes required in upstream except the bump.  I think I can just rebase this to bump that dependency as well.

**Comment by smarterclayton** [comment]
Will get https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/284 merged first

**Comment by smarterclayton** [comment]
Fixed in #25

**Pull request closed without merging**
