### PR TITLE
Bug 2002281: 4.8: pkg/resourceprovider: guard from negative metrics

### PR DESCRIPTION
**Pull request by dgrisonnet**
Cherry-pick of 0b3ac78d1922e05141ca2b3095bec0997b628062 on release-4.8.

### CODE REVIEW

**Comment by juzhao** [comment]
tested with the fix, watched for a while, did not see negative value for `oc adm top nodes`
/label qe-approved

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

adding cherry-pick approved

**Pull request merged**
