### PR TITLE
MON-3489: Bump openshift/k8s-prometheus-adapter to v0.11.2

### PR DESCRIPTION
**Pull request by simonpasquier**
Supersedes #93

### CODE REVIEW

**Comment by simonpasquier** [comment]
/retitle MON-3489: Bump openshift/k8s-prometheus-adapter to v0.11.2

**Comment by simonpasquier** [comment]
/label acknowledge-critical-fixes-only

No functional change here.

**Review by slashpai — COMMENTED** [review]
/lgtm

**Review by marioferh — COMMENTED** [review]
/lgtm

**Pull request merged**
