### PR TITLE
Merge tag directxman12/v0.4.1 into openshift/master

### PR DESCRIPTION
**Pull request by mxinden**
Instead of using the fancy method by @s-urbaniak:

``` bash
git fetch
git checkout upstream/master
git checkout -b merge
git checkout downstream/master
echo 'merge upstream' | git commit-tree merge^{tree} -p HEAD -p merge
somecommitsha
git checkout somecommitsha
```

this PR simply does a:

```bash
git checkout openshift/master 
git merge v0.4.1
```

as suggested by @simonpasquier.

Reasoning behind this is that https://github.com/openshift/k8s-prometheus-adapter/pull/7 is missing #6 and thereby the Dockerfiles in the root of the directory. Doing a `git log --full-history -- Dockerfile` reveals that the merge commit itself deletes them.

Do people have thoughts on the way we want to proceed here?

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@mxinden the easier, the better! :+1: Back then the hacky way was necessary as the merge wasn't that easy.

**Comment by mxinden** [comment]
Thanks @s-urbaniak for the details.

Merging this branch locally (`git checkout master && git reset --hard openshift/master && git merge merge-directxman12`) results in a _fast-forward_ with the below git log preserving both _openshift_ as well as _directxman12_ git commit sha's.

@brancz would we need an exception to get this merged?

```git
commit 8ab4dc7b78c4376ddb97ef37e5297219c742902f (HEAD -> master, mxinden/merge-directxman12, merge-directxman12)
Merge: 19f9a95 dce283d
Author: Max Leonard Inden <IndenML@gmail.com>
Date:   Thu Jan 31 18:17:31 2019 +0100

    Merge tag 'v0.4.1' into HEAD
    
    v0.4.1

commit 19f9a956abcf670c44b2d49ed90cc337d94b4b9d (openshift/master, openshift/HEAD)
Merge: b1d7720 bb5aea8
Author: Frederic Branczyk <fbranczyk@gmail.com>
Date:   Tue Jan 8 21:45:42 2019 +0100

    Merge pull request #6 from pgier/add-openshift-dockerfile
    
    Add Dockefiles for openshift CI

commit bb5aea8d5551c9a1f6ef6a804766de06a1799222
Author: Paul Gier <pgier@redhat.com>
Date:   Tue Jan 8 14:37:35 2019 -0600

    Add Dockefiles for openshift CI

commit b1d7720326696d6f6c01a67517382dcb97a4be75
Merge: eee898e ae8bab2
Author: Frederic Branczyk <fbranczyk@gmail.com>
Date:   Tue Jan 8 21:23:37 2019 +0100

    Merge pull request #5 from pgier/add-owners-file
    
    add OWNERS file for CI automation

commit ae8bab2228c5ec5615153990508e3aaf4d190d14
Author: Paul Gier <pgier@redhat.com>
Date:   Tue Jan 8 14:21:14 2019 -0600

    add OWNERS file for CI automation

commit dce283def1ad819be55dd2a611f85084e4981313 (tag: v0.4.1, directxman12/master, merge)
Merge: 1e5a868 7624952
Author: Frederic Branczyk <fbranczyk@gmail.com>
Date:   Thu Dec 13 16:03:49 2018 -0800

    Merge pull request #148 from brancz/empty-err
    
    Fix empty pod or node list resulting in an error

commit 76249528703ce650d7d5f596a9418d7a98a4ef86
Author: Frederic Branczyk <fbranczyk@gmail.com>
Date:   Thu Dec 13 15:50:02 2018 -0800

    resourceprovider: Add comments on possible nil results

commit e9ef0bb4d0e28c31ae81f3188b657ce63adf60ee
Author: Frederic Branczyk <fbranczyk@gmail.com>
Date:   Tue Dec 11 10:21:21 2018 -0800

    Fix empty pod or node list resulting in an error

[...]
```

**Comment by simonpasquier** [comment]
When the merge is big or if I have doubts, I compare the upstream tag and the PR like this:

https://github.com/DirectXMan12/k8s-prometheus-adapter/compare/v0.4.1...mxinden:merge-directxman12

The diff is usually small enough that I can review it and spot merge conflicts that weren't resolved properly.

**Comment by brancz** [comment]
As this is a bug fix, no need for exception.

/lgtm

**Comment by mxinden** [comment]
Tested basic `kubectl top` commands on Openshift 4.0 with `quay.io/mxinden/k8s-prometheus-adapter:v0.4.1-openshift`.

**Pull request merged**
